/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiQueryRouteImport } from './routes/api/query'
import { Route as ApiPublicProcessDocumentsRouteImport } from './routes/api/public/process-documents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiQueryRoute = ApiQueryRouteImport.update({
  id: '/api/query',
  path: '/api/query',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProcessDocumentsRoute =
  ApiPublicProcessDocumentsRouteImport.update({
    id: '/api/public/process-documents',
    path: '/api/public/process-documents',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/query': typeof ApiQueryRoute
  '/api/public/process-documents': typeof ApiPublicProcessDocumentsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/query': typeof ApiQueryRoute
  '/api/public/process-documents': typeof ApiPublicProcessDocumentsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/api/query': typeof ApiQueryRoute
  '/api/public/process-documents': typeof ApiPublicProcessDocumentsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/api/query' | '/api/public/process-documents'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/api/query' | '/api/public/process-documents'
  id: '__root__' | '/' | '/api/query' | '/api/public/process-documents'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ApiQueryRoute: typeof ApiQueryRoute
  ApiPublicProcessDocumentsRoute: typeof ApiPublicProcessDocumentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/query': {
      id: '/api/query'
      path: '/api/query'
      fullPath: '/api/query'
      preLoaderRoute: typeof ApiQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/process-documents': {
      id: '/api/public/process-documents'
      path: '/api/public/process-documents'
      fullPath: '/api/public/process-documents'
      preLoaderRoute: typeof ApiPublicProcessDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ApiQueryRoute: ApiQueryRoute,
  ApiPublicProcessDocumentsRoute: ApiPublicProcessDocumentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
